name: 🎥 Add a Dance Video
description: Suggest a new Salsa or Bachata video to add to the app
title: 'Add a new [Salsa/Bachata] video: "[Video Title Here]"'
labels: ['video contribution', 'good first issue']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for contributing! 🙌

        We're always looking for quality Salsa and Bachata videos to add to Bailapp!

        **⚠️ Before submitting:** Don't forget to update the issue title above to match your video!
        Example: `Add a new Salsa video: "Setenta Tutorial"` or `Add a new Bachata video: "Basic Steps"`

        Before submitting, please:
        - Check that the video doesn't already exist in the app
        - Make sure it's a good quality tutorial (clear explanations, good camera angles)
        - Read our [Adding Videos Guide](https://github.com/PolThm/bailapp/blob/main/ADDING_VIDEOS.md)

  - type: input
    id: video-url
    attributes:
      label: YouTube URL
      description: The full YouTube URL of the video
      placeholder: https://www.youtube.com/watch?v=...
    validations:
      required: true

  - type: dropdown
    id: video-type
    attributes:
      label: Video Type
      description: Is this a regular video or a YouTube Short?
      options:
        - Classic Video (regular YouTube video)
        - YouTube Short (vertical format)
    validations:
      required: true

  - type: dropdown
    id: dance-style
    attributes:
      label: Dance Style
      description: What type of dance is this?
      options:
        - Salsa
        - Bachata
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity Level
      description: What level is this tutorial for?
      options:
        - Basic (beginner friendly)
        - Basic-Intermediate
        - Intermediate
        - Intermediate-Advanced
        - Advanced
    validations:
      required: true

  - type: input
    id: video-title
    attributes:
      label: Video Title
      description: A short, catchy name for the video
      placeholder: e.g., "Cross Body Lead Tutorial"
    validations:
      required: true

  - type: textarea
    id: video-description
    attributes:
      label: Description
      description: A brief description of what this video teaches
      placeholder: Describe what makes this video useful and what dancers will learn
    validations:
      required: true

  - type: input
    id: start-time
    attributes:
      label: Start Time (optional)
      description: If the tutorial doesn't start at the beginning, specify the start time
      placeholder: e.g., 0:30 or 1:15

  - type: input
    id: end-time
    attributes:
      label: End Time (optional)
      description: If the tutorial is part of a longer video, specify the end time
      placeholder: e.g., 3:45

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this video doesn't already exist in the app
          required: true
        - label: The video has good quality (clear explanations, good camera angles)
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/PolThm/bailapp/blob/main/CONTRIBUTING.md)
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### What happens next?

        A maintainer will review your suggestion and either:
        - Add the video themselves
        - Guide you to create a Pull Request if you'd like to contribute directly

        Thank you for helping make Bailapp better! 💃🕺
